### ISSUE TITLE
Slash doesn't work with poetry

### ISSUE THREAD

**Issue by d1618033** [getslash/slash#1004]
```
❯ poetry add slash
Using version ^1.9.0 for slash

Updating dependencies
Resolving dependencies... (20.3s)

[RecursionError]
maximum recursion depth exceeded while calling a Python object
```

Attached: result of ```poetry add -vvv slash``` and `pyproject.toml`

[slash_and_poetry_dont_work_together.tar.gz](https://github.com/getslash/slash/files/4029630/slash_and_poetry_dont_work_together.tar.gz)

Probably related to [this](https://github.com/python-poetry/poetry/issues/1238) issue, and due to the duplication IPython in `requirements.txt`:
```
IPython==1.2.1; implementation_name=='pypy'
IPython; implementation_name!='pypy'
```

**Comment by d1618033** [comment]
Issue with poetry.

**Comment by gragib** [comment]
This is an issue with `poetry`: https://github.com/python-poetry/poetry/issues/3363.
This is my workaround:
```yaml
slash = {version = "*", markers = "implementation_name == 'cpython'"}
```
