### ISSUE TITLE
Add option to display duplicate tests in `slash list`

### ISSUE THREAD

**Issue by yaelmi3** [getslash/slash#1018]
Running tests from files ` slash run -v some_suite` is widely used in our org (Infi). Since these files may contain both folders, modules and separate tests, there are many occurrences where we get duplicated tests within the suite, without intending. While `slash list -f ...` displays only unique tests and `slash run` executes all the collected tests, we would like to create an internal validation util to eliminate these duplicates. In order to achieve it, we would like to add an option to `slash list` to `show-repeats`, which will be disabled by default

**Comment by vmalloc** [comment]
@yaelmi3 can this be closed now?

**Comment by yaelmi3** [comment]
Yes.
