### ISSUE TITLE
slash tests with complex assertions end with `No module named '_pytest'` when pytest is not installed

### ISSUE THREAD

**Issue by yaelmi3** [getslash/slash#1020]
```
def test_pytest():
    assert None and None
```
Running the following test, when pytest is not installed, result in the following:

```
 /Users/ymintz/infi/infi_proj/stokado/tests/test_bla.py:27
>    assert None and None == None
E    ModuleNotFoundError: No module named '_pytest'
```

It seems that https://github.com/vmalloc/dessert/blob/develop/dessert/rewrite.py#L702 uses attempts to import pytest, but since it's neither part of dessert requirements nor slash requirements, the tests with fail due to this context usage: https://github.com/getslash/slash/blob/develop/slash/loader.py#L194

@vmalloc:  I'm not sure whether pytest should be simply added to dessert requirements or there's a better solution for this issue

**Comment by ayalash** [comment]
@yaelmi3 It is a bug in commit https://github.com/vmalloc/dessert/commit/7a0295ff91ec701715cf8d44ee61437bb8bfe4d5 which I wrote 7 months ago.
It should be fixed in dessert and slash should depend on the newer version.

**Comment by ayalash** [comment]
@yaelmi3 I opened an issue for dessert https://github.com/vmalloc/dessert/issues/12 and I'll work on it shortly

**Comment by yaelmi3** [comment]
Resolved by @ayalash
