### ISSUE TITLE
support local per-directory conftest.py file for loading plugins

### ISSUE THREAD

**Issue by linus-gates** [getslash/slash#1044]
`pytest`'s `conftest.py` is a cool & useful feature, you already know this since it is already in use to test `slash`.
It would be nice if `slash` will support it as well

**Comment by vmalloc** [comment]
Slash actually supports this concept through the `slashconf.py` files. However since pytest and slash are different in many aspects and the "discovery" process is more implicit in py.test, there is no support for the same exact conftest files in Slash...
