### ISSUE TITLE
slash doesn't work with python3.6 due to IPython's recent release

### ISSUE THREAD

**Issue by d1618033** [getslash/slash#1048]
IPython recently (since version 7.17.0, released in Aug 2020) decided to drop support for Python>3.6. 

[Slash still supports Python3.6](https://github.com/getslash/slash/blob/develop/setup.cfg#L4).
 
A possible solution is to modify the requirements file so that if python==3.6, it will use IPython<7.17.0

Working on a pull request right now to do just that

**Comment by vmalloc** [comment]
sounds like a reasonable solution. Thanks!
