### ISSUE TITLE
Add this.test_start and this.test_end to fixture arguments

### ISSUE THREAD

**Issue by vmalloc** [getslash/slash#195]

**Comment by eplaut** [comment]
Hi @vmalloc!

This issue becomes more and more important to us. can you prioritize it? (if needed, give me leads ho to implement it)

many thanks!

**Comment by vmalloc** [comment]
@eplaut adding this to the 1.1.0 release

**Comment by vmalloc** [comment]
@eplaut the `develop` branch now contains an initial implementation of this mechanism. Feedback at this point would be greatly appreciated...

**Comment by eplaut** [comment]
@vmalloc this looks great

**Comment by eplaut** [comment]
@vmalloc , we encountered an issue with this implementation.
once a session fixture is loaded, its `test_start` and `test_end` always run (also when the fixture is not in use)
```
import slash

@slash.fixture(scope='session')
def fix_a(this):
    print 'session start (a)'

    @this.test_start
    def start():
        print 'test start (a)'

    return 'a'

@slash.fixture(scope='session')
def fix_b(this):
    print 'session start (b)'

    @this.test_start
    def start():
        print 'test start (b)'

    return 'b'

def test_a(fix_a):
    pass

def test_b(fix_b):
    pass

def test_c():
    pass
```

```
$ slash run -v test.py
3 tests collected   
[2016-11-02 13:10:53] a.py:test_a
session start (a)
test start (a)
[2016-11-02 13:10:53] a.py:test_b
session start (b)
test start (a)
test start (b)
[2016-11-02 13:10:53] a.py:test_c
test start (a)
test start (b)
```

**Comment by vmalloc** [comment]
What do you mean not in use? was it activated?

Once activated, a session fixture is considered active throughout the session, so it's as if all tests need it...

**Comment by eplaut** [comment]
ok. Now I understand where I was wrong.
I was under assumption that the `test_start` and `test_end` should occur only when the fixture been sent to the test. I missed the fact that it relevant as long as the fixture is active.

Thanks!

**Comment by vmalloc** [comment]
Sure, no problem
