### ISSUE TITLE
Add option to run tests in parallel on multiple subprocesses

### ISSUE THREAD

**Issue by yotamr** [getslash/slash#213]
Akin to nose's multiprocess, it would be useful to distribute slash tests across several worker processes.

**Comment by eplaut** [comment]
@vmalloc can you estimate if this feature will be available?

**Comment by vmalloc** [comment]
*if* it will be available = yes.
*when* it will be available is slightly trickier. We're currently trying to stabilize Backslash, and I think it's next in priority after that.

BTW - we do plan on adding the option to parallelize based on Backslash (with Backslash being the entity who knows what succeeded and what needs to be run), so it might help your particular purpose as well...

**Comment by eplaut** [comment]
Many thanks! I'll wait for it

**Comment by vmalloc** [comment]
Already implemented in 1.3.0
