### ISSUE TITLE
No dessert output in Python 3

### ISSUE THREAD

**Issue by r-darwish** [getslash/slash#315]
I'm not sure whether it's an issue with Dessert or an issue with the integration of Dessert in Slash.

https://gist.github.com/r-darwish/f25ddb7cb4eca38dab0c

The above example shows a simple test that contains an assertion, and the output printed by Slash in both Python 2 and Python 3

**Comment by vmalloc** [comment]
Related to https://github.com/vmalloc/emport/issues/2

**Comment by vmalloc** [comment]
Experimental fix pushed to branch `experimental` in emport.

**Comment by vmalloc** [comment]
Closing assuming this doesn't happen anymore
