### ISSUE TITLE
--with-xunit crashes when using skipped without giving reason

### ISSUE THREAD

**Issue by hagai26** [getslash/slash#376]
This will work:
```python
@slash.skipped("no reason")
def test...
```

This will raise error:
```python
@slash.skipped
def test...
```
The error is:
"cannot serialize %r (type %s)" % (text, type(text).__name__)
TypeError: cannot serialize None (type NoneType)

This is because it tries to write the default reason which is None to the xml.

**Comment by vmalloc** [comment]
Fixed in 0.19.2. Thanks!
