### ISSUE TITLE
`before` and `after` methods don't accept fixtures in arguments

### ISSUE THREAD

**Issue by sergei-dyshel** [getslash/slash#383]
Basing on [this](https://slash.readthedocs.org/en/master/fixtures.html#opting-out-of-fixtures) I tried to use fixture in test class's `before` method and it didn't work.

It shouldn't work according to [these lines](https://github.com/getslash/slash/blob/develop/slash/core/test.py#L114).

**Comment by vmalloc** [comment]
@sergei-dyshel can you post your code? What exactly did you try?

**Comment by vmalloc** [comment]
Ok, I see what you mean now. This is actually a small confusion that comes from the internals - where parameters are treated very similarly to fixtures, and it somehow slipped that we don't support actual fixtures there.

Will fix this soon.

**Comment by vmalloc** [comment]
Fixed in 0.19.3

**Comment by vmalloc** [comment]
@sergei-dyshel thanks for reporting!

**Comment by sergei-dyshel** [comment]
Thanks! That was quick ;)

-- 
Regards,
Sergei Dyshel
