### ISSUE TITLE
Pressing `Ctrl-C` during repeated run (`-o run.repeat_each=N`) interrupts only current iteration.

### ISSUE THREAD

**Issue by sergei-dyshel** [getslash/slash#392]
I don't know if it's a bug or a feature, but interrupting the whole run seems more logical to me :smile:

**Comment by vmalloc** [comment]
I can't get it to reproduce on my end - is it possible the interrupt is caught in a plugin somewhere? Could you build a minimalistic scenario to reproduce it (you can `raise KeyboardInterrupt` from a test and it should have the same effect)

**Comment by sergei-dyshel** [comment]
Can't reproduce it with simple example. I use a chain of wrappers which call `main_entry_point()` in the end. May be the exception get's swallowed somewhere. I'll reopen this issue when I have more info.
