### ISSUE TITLE
Disable hooks on skipped tests.

### ISSUE THREAD

**Issue by sergei-dyshel** [getslash/slash#399]
Is there an option to disable running `test_start`, `test_end` etc. hooks for skipped tests?

**Comment by vmalloc** [comment]
No - but they're not triggered on *not run* tests (tests that have unmet requirements). This is the main difference between requirements and skips

**Comment by vmalloc** [comment]
Generally once a test has started there's no guarantee of what it already accomplished before being skipped, so we want to preserve hook calling for those...

**Comment by sergei-dyshel** [comment]
I see. In that case, what's the purpose of *skipped* attribute? Currently I use to mark tests which are failing because of some bug and when the bug gets resolved I remove the skip. But some heave test setup/teardown code (like starting VMs) still runs for skipped tests.

**Comment by sergei-dyshel** [comment]
> Generally once a test has started there's no guarantee of what it already accomplished before being skipped, so we want to preserve hook calling for those...

Even if the whole test method/class is marked with `skipped` decorator?

**Comment by vmalloc** [comment]
You're raising a valid point. `@skipped` was added before we had the concept of requirements, so it operates differently. I think we can change it to use requirements, so that it won't fire hooks. Would that work for you?

**Comment by sergei-dyshel** [comment]
Currently I'm using some dirty workaround (involving `__slash__skipped__`) which solves this. I think the proper way is to use something like `@slash.requires(issue_solved('issue#100'))` and integrate with issue tracker.

**Comment by vmalloc** [comment]
@sergei-dyshel so what I wrote above is ok for you right? If we make the skipped decorator use requirements instead...

**Comment by sergei-dyshel** [comment]
Absolutely :smile:

**Comment by vmalloc** [comment]
Opened #400 for the new improvement. Closing this one.
