### ISSUE TITLE
Add coverage plugin

### ISSUE THREAD

**Issue by eplaut** [getslash/slash#430]
It would be wonderful to have coverage report for test session.

**Comment by vmalloc** [comment]
Sounds like a great idea! PRs are more than welcome!

**Comment by vmalloc** [comment]
@eplaut I added the missing arguments to the proposed branch. Would appreciate if you could take it to a spin and let me know what needs improving.

I read the reference for coverage.py and am pretty confident adding multi-process support would be easier than the complexity in pytest-cov.

**Comment by eplaut** [comment]
Many thanks, it looks great.

One issue, I think because of the differences between `activate` and `before_session_start` methods the report look a little bit strange, it misses the imports and function declaration.

**Comment by vmalloc** [comment]
@eplaut thanks for the feedback! I moved the collection start to `activate` to fix the issue. Please let me know if it works for you now.

**Comment by eplaut** [comment]
@vmalloc I've tested `feature/coverage` branch and it looks great. please put it in the next version.

Many thanks!

**Comment by vmalloc** [comment]
Sure, no problem!

**Comment by eplaut** [comment]
Hi @vmalloc, Can you add the coverage plugin to the current version (0.20)?

Many thanks!

**Comment by vmalloc** [comment]
@eplaut unfortunately no, as we don't add new features to bugfix releases. You can try running with the develop branch, which will soon become v1.0, and has lots of other improvements as well

**Comment by eplaut** [comment]
@vmalloc, I tried using develop, but it looks like `session_end` method doesn't run (and there is not report)

**Comment by vmalloc** [comment]
@eplaut Can you provide something that reproduces the issue? I don't see such a behavior with the current version....

**Comment by eplaut** [comment]
I'm trying to write some library, and there are no `.coverage` or `htmlcov` in the folder.
I've tried to debug it, and didn't seen any indication that the method ran (prints etc.)

**Comment by vmalloc** [comment]
@eplaut `--with-coverage`?

**Comment by eplaut** [comment]
yes. the activate method run for sure, but not the `session_end`

**Comment by eplaut** [comment]
add `slash.plugins.manager.get_plugin('coverage').session_end()` in the end of the test does work

**Comment by vmalloc** [comment]
@eplaut no that's not how it should be done. There's probably a bug somewhere. Will take a look.

**Comment by eplaut** [comment]
I'm sure, just checked that the environment is good.
If you need me to debug, just tell me what to do.

**Comment by vmalloc** [comment]
Found it. Opening linked issue

**Comment by vmalloc** [comment]
Opened #449

**Comment by vmalloc** [comment]
Discussion moved to linked issue
