### ISSUE TITLE
_self as self-reference doesn't work in version 1.0.0

### ISSUE THREAD

**Issue by eplaut** [getslash/slash#463]
```
import slash
class TestCaseError(slash.Test):
    def test(_self):
        pass
```
return `ERROR: Loading test.py:test: Fixture '_self' not found!`
It worked on 0.20.3, and needed for closured tests creation.

**Comment by vmalloc** [comment]
Out of curiosity, what do you mean by closured tests creation, and how exactly does this contribute?

**Comment by eplaut** [comment]
It is legacy code (meaning large monster, that will be hell to change), that doesn't use proper fixtures and parametrize.
I'm sure that using parametrize can save the closure thing, but it will be hell (and long).

**Comment by vmalloc** [comment]
If the problem is that an internal method is using `self`, it would be better to rename that one to `_self` instead of the outer one... Chancing the logic of fixture lookup is not trivial at all and I fear doing it without good reasons...

**Comment by eplaut** [comment]
This solution solved the problem. I will change it on my side. thanks!
