### ISSUE TITLE
Running python interpreter inside site-packages/slash directory results in error

### ISSUE THREAD

**Issue by sergei-dyshel** [getslash/slash#474]
```bash
[user@host ~]$ cd /usr/lib/python2.7/site-packages/slash
[user@host slash]$ /usr/bin/python
Traceback (most recent call last):
  File "site.py", line 1, in <module>
    import os
  File "/usr/lib64/python2.7/os.py", line 49, in <module>
    import posixpath as path
  File "/usr/lib64/python2.7/posixpath.py", line 17, in <module>
    import warnings
  File "warnings.py", line 3, in <module>
    import logbook
ImportError: No module named logbook
[user@host slash]$ 
```

While it's probably OK to have a module with same name as standard one ([warnings](https://docs.python.org/2/library/warnings.html)), this particular error disrupts  normal work of programs which have an embedded python interpreter (such as Vim, in my case).

**Comment by vmalloc** [comment]
@sergei-dyshel how is this a slash issue? you didn't run anything slash-related in the above example...

**Comment by vmalloc** [comment]
It is ok to have a module with the same name as a built-in module inside your own package. this is why `from __future__ import absolute_import` exists
