### ISSUE TITLE
[xunit-plugin] Write xml file on test_end

### ISSUE THREAD

**Issue by eplaut** [getslash/slash#485]
Hi,

I was wondering if it is ok to change xunit-plugin to update the file on each `test_end` and not only when the session is over.
(change is trivial, so I asked before suggesting a PR)

Many thanks!

**Comment by vmalloc** [comment]
Sure, could be a good idea. I only hope that for large suites this wouldn't slow down `test_end` significantly, because each time all the results would be written. A quick benchmark of the current code for large suites might shed some light on that concern...

**Comment by eplaut** [comment]
Hi,
benchmark of 1000 `pass` tests (using `repeat-all`) takes 3 seconds.
adding naive implementation extend it to 10 seconds.

After reconsidering the requirements (getting partial xml file if session aborted), I've notice the differences between `session_end` and `result_summary` ("regardless of the reason for termination" helped there). changing xunit plugin to `session_end` wrote the xml file even if the session ended due to SIGTERM.

Is this change acceptable?

**Comment by vmalloc** [comment]
Yes. I think it's reasonable.
