### ISSUE TITLE
slash.plugins.manager.get_plugin missing from the Plugins documentation

### ISSUE THREAD

**Issue by eliadl** [getslash/slash#492]
Please add `slash.plugins.manager.get_plugin` to the Plugins documentation.
Personally I store a flag attr in my plugin which can modify its behavior.
This enables me to let fixtures determine the plugin's behavior.

**Comment by vmalloc** [comment]
@eliadl it's already in the API docs: http://slash.readthedocs.io/en/master/api.html#slash.plugins.PluginManager.get_plugin
Is that what you mean?

**Comment by eliadl** [comment]
@vmalloc Yes, but this is the API page.
I think it should also be mentioned (even if not *fully* detailed) **at the Plugins page:**
http://slash.readthedocs.io/en/master/plugins.html

**Comment by vmalloc** [comment]
@eliadl I see. Ok. If you feel like phrasing it in a PR that would be very much appreciated. Otherwise I'll do it soon.

**Comment by eliadl** [comment]
Merged here: https://github.com/getslash/slash/pull/493
