### ISSUE TITLE
[Question] Getting a list of test durations

### ISSUE THREAD

**Issue by amibiz** [getslash/slash#503]
Does slash support reporting of test execution time (durations)?
Something like:
http://doc.pytest.org/en/latest/usage.html#profiling-test-execution-duration

**Comment by vmalloc** [comment]
Currently not, but it can be easily added to the result object and reported. It is also relatively easy to write a plugin that does this, but I agree that the durations should be kept on the result object since it's cheap.

**Comment by amibiz** [comment]
So I have implemented a simple plugin that reports the duration of tests. I not familiar with the `result object`, will look into it.
10x
