### ISSUE TITLE
what are some subjective differences compared to pytest?

### ISSUE THREAD

**Issue by rlam3** [getslash/slash#506]
what are some subjective differences compared to pytest?

i'm thinking of moving away from unittest to either pytest or slash... would like more insight on this. thanks!

**Comment by vmalloc** [comment]
This is a very good question, and we get asked it from time to time. There are many relatively minor
superficial differences between Pytest and Slash (like the ability to parametrize fixtures directly,
logging control and others) but those are all, in my opinion, beside the point.

The main difference is in the project's focus. Pytest was created as a successor to nose/unittest,
and as such its primary focus tends to be unit tests. This implies certain defaults (like
stdout/stderr capturing) and certain sets of features which are more likely to be implemented for
it. We personally love pytest and use it to test Slash itself, as you may have noticed.

The main project for which we wrote Slash involved testing an external product. As such, it was less
about maintaining individual state for each test and setting it up again later, and more about
building a consistent state for the entire test session -- syncing with the test "subject" before the first test, performing validations between tests, recycling objects and entities between tests etc.

What was missing for us in Pytest became clear after a certain period of active development -- Pytest, being focused around the tests being written, lacks (some) facilities to deal with everything around and between the tests.
One specific example for us was widely-scoped cleanups (like tests registering cleanups that are to happen at the end of the session or module) - in this case it was difficult to tie the error to the entity that created the cleanup logic.

While pytest can be loosely thought of as a tool, Slash can be thought of as a framework. It puts much more emphasis on letting you build on top of it, set up your environment and integrate with external services (we ourselves
built Backslash as a centralized reporting solution for it, for instance). The distinction isn't clear-cut though.

I recommend taking a closer look at both, keeping in mind what you need eventually -- if you need unit tests that replace legacy `unittest` tests with little or no tailoring in between or ecosystem support, you can safely go with pytest.
If tests are not a by-product of what you do but instead are your main goal, and you see yourself building and evolving an in-house infrastructure for tests, Slash could be a better fit for you.

Also keep in mind that Pytest has been around much longer, so if you need a vast variety of plugins written by the community, that's a specific battle that Slash would lose at its current state.

**Comment by vmalloc** [comment]
For more information on specific features that were added recently (a lot of them unique to Slash) you can take a look at our [changelog](http://slash.readthedocs.io/en/master/changelog.html)
