### ISSUE TITLE
Add Result.get_log_paths()

### ISSUE THREAD

**Issue by ayalash** [getslash/slash#511]

**Comment by ayalash** [comment]
@vmalloc I need some help with the changelog & cookbook section of this issue.
You can see my current branch (`ayalas/get_log_paths`) which is WIP.
Does my changelog message good enough?
What do you think I should add for the cookbook in this subject.

p.s.  I added docstrings for the Result's relevant methods, as we discussed, but I don't think they are good enough.

**Comment by vmalloc** [comment]
@ayalash I think the cookbook should be something like:

`---------`
# Adding Multiple Log Files to the Current Result
Slash result objects contain the main path of the log file created by Slash (if logging is properly configured for the current run).

In some cases it may be desirable to include multiple log files for the current test. This can be useful, for example, if the current test runs additional tools or processes emitting additional logs:

`----------`

Then we can add an example of a simple test running an external command-line-based tool, giving it the generated log path with a `-L` argument or something
