### ISSUE TITLE
add ability to exclude specific cartesian product of parameters

### ISSUE THREAD

**Issue by mordi42** [getslash/slash#528]
following #369 (Add utility to narrow customizations of a fixture), it would be useful to exclude a specific permutation (similar to 'Specifying Multiple Arguments at Once' option).
e.g. 
```
@slash.parametrize('topping', ['onion', 'olives', 'pepperoni'])
@slash.parameters.toggle('vegan')
@slash.exclude(('topping','vegan'),[('pepperoni',True)])
test_pizza(topping, vegan):
```

**Comment by vmalloc** [comment]
This is a good idea. We will try to add it to our next milestone. Thanks!
