### ISSUE TITLE
Switch to pbr

### ISSUE THREAD

**Issue by vmalloc** [getslash/slash#529]

**Comment by ayalash** [comment]
@vmalloc In `setup.py` there is:
```
if _PYTHON_VERSION < (2, 7) or _IS_PYPY:
    install_requires.insert(0, "ptyprocess==0.4") # 0.5 dropped 2.6 support
```
Is there a reason why its first in the `install_requires` list?
Should we keep the 0.4 version?  The comment says that its due to python2.6 & as far as I know we don't support it anymore as well...

**Comment by vmalloc** [comment]
We can drop it IMO.
