### ISSUE TITLE
[Question] Support for class level setup/teardown 

### ISSUE THREAD

**Issue by amibiz** [getslash/slash#533]
I was wondering if slash supports class level (scope?) setup/teardown.
Referencing pytest:
http://doc.pytest.org/en/latest/xunit_setup.html#class-level-setup-teardown

**Comment by vmalloc** [comment]
@amibiz no, we don't support it. We're also moving away from class-based tests because it has many shortcomings compared to fixture-based test structure, so I'm not sure we're going to support it in the near future.

**Comment by amibiz** [comment]
Thanks :)

**Comment by vmalloc** [comment]
Sure, no problem
