### ISSUE TITLE
Support naming for test parameters

### ISSUE THREAD

**Issue by ayalash** [getslash/slash#590]
Parameters naming has two goals:
* Allow tracking a specific parameter value regardless of its index
* Better `repr`ing
This feature should support all slash iteration options: `slash.parametrize`, `slash.parameters.iterate` and `generator_fixture`.

**Comment by vmalloc** [comment]
Current suggestion is to have:
```python
from slash import param, parametrize

@parametrize('arg', [
    param('name1', value1),
    param('name2', value2),
])
def test_something(arg):
    ...
```

As an alternative, equivalent syntax, it would be possible to:

```python
from slash import param, parametrize

@parametrize('arg', [
    value1 // param('name1'),
    value2 // param('name2'),
])
def test_something(arg):
    ...

**Comment by vmalloc** [comment]
Tasks: 

- [ ] Add test for multi-parameter parametrization with `slash.param`
