### ISSUE TITLE
Is it possible to run a specific test?

### ISSUE THREAD

**Issue by jeremylima** [getslash/slash#699]
For example in the file tests.py I have the following:

```
class example(Test):

    def test_1():
        pass
    def test_2():
        pass
```

with 

> slash run test.py

 i can run all the test, but exists a way to run test_1 or test_2 in specific?

**Comment by vmalloc** [comment]
@jeremylima of course. Aside from the fact that your example needs a small fix (adding the `self` argument), running:

```
$ slash run /path/to/test.py:example.test_1
```
should run the same method. Alternatively you can filter tests to run what you want:
```
$ slash run /path/to/tests -k test_1
```

**Comment by jeremylima** [comment]
Great. Thanks!
