### ISSUE TITLE
Error hides failure

### ISSUE THREAD

**Issue by ViktorFagerlind** [getslash/slash#706]
When reporting slash.add_error followed by slash.add_failure slash reports 0 failures and 1 error.

Session summary:
=============================== Session Summary ===============================
== #1: t06_bc1553.py:test_pe ==================================================
 - Additional Details:
    > Log: 'logs\\f848f34c-e627-11e7-9bf5-e4a47117276b_0/f848f34c-e627-11e7-9bf5-e4a47117276b_0_1.log'
 - 1/2 E (2017-12-21 09:21:40 +01:00):   - - - - - - - - - - - - - - - - - - -
 BC1553 Error!
 c:\anaconda2\envs\python36\lib\runpy.py:85
>    exec(code, run_globals)
 C:\ANACONDA2\envs\python36\Scripts\slash.exe\__main__.py:9
>    sys.exit(main_entry_point())
 c:\Utilities\python-tem\t06_bc1553.py:47
>    slash.add_error("BC1553 Error!")
E    BC1553 Error!
 - 2/2 F (2017-12-21 09:21:40 +01:00):   - - - - - - - - - - - - - - - - - - -
 BC1553 Failure!
 c:\anaconda2\envs\python36\lib\runpy.py:85
>    exec(code, run_globals)
 C:\ANACONDA2\envs\python36\Scripts\slash.exe\__main__.py:9
>    sys.exit(main_entry_point())
 c:\Utilities\python-tem\t06_bc1553.py:48
>    slash.add_failure("BC1553 Failure!")
F    BC1553 Failure!
 Session ended. 0 successful, 0 skipped, 0 failures, 1 errors. Total duration: 00:00:05

**Comment by vmalloc** [comment]
Hi! Thanks for reporting!
I’ll try to explain the current logic. At the moment the counters at the bottom of the console output count tests, and not individual errors. This means they have to make sense (failures+errors+success=total). Since errors can be thought of as “uncontrolled failures” the idea is to count any test with an error as an error and not a failure. 

Having said that we are open to suggestions regarding how to make this clearer for new users

**Comment by ViktorFagerlind** [comment]
OK, i did not realize that the numbers referred to the number of tests and not individual failures/errors. The current logic works for me now that I understand. A suggestion to make it more clear is to say "failed" instead of failures and "erroneous" instead of errors. That would make it easier to understand the reference to tests.

**Comment by vmalloc** [comment]
Good idea. I'll open a new ticket to fix that. Thanks for reporting!

**Comment by vmalloc** [comment]
Opened #709
