### ISSUE TITLE
interruptions during session scope are not registered on the session result properly and don't fail the session as expected

### ISSUE THREAD

**Issue by vmalloc** [getslash/slash#744]

**Comment by ayalash** [comment]
@vmalloc Does this issue relates to #774 ?

**Comment by vmalloc** [comment]
@ayalash I can't seem to reproduce this. Not on session_start and not on before_session_start... I'm opening a PR with a test for these cases, but otherwise closing this issue unless we find a way to reproduce....

**Comment by ayalash** [comment]
@vmalloc I also did not succeed to reproduce it. You can close this issue, I'll open a new one in case it happen again.
