### ISSUE TITLE
Log cleanup leaves broken symlinks

### ISSUE THREAD

**Issue by drrlvn** [getslash/slash#749]
The symlinks to last session, test etc. are not removed so they remain broken after the cleanup.

**Comment by vmalloc** [comment]
It goes without saying they will be removed, not restored to their previous value... If you had a last session link before your run, you lose the link...

**Comment by drrlvn** [comment]
Of course, that's the behavior I expected.

**Comment by vmalloc** [comment]
We decided not to fix this. It is hard to solve it assuming you have multiple sessions running at once from the same machine. I think assuming one chooses to delete his/her own logs every time (potentially keeping failed ones) - he or she will be fine with keeping these links (or configuring them out of existence, which is another option that becomes reasonable if you have at most one log at any given moment)
