### ISSUE TITLE
Native warnings should be filterable

### ISSUE THREAD

**Issue by yotamr** [getslash/slash#752]
We're using a particularly warningy' third-party library that inundates the logs with many native warnings. The filter that SessionWarnings uses should be made configurable, so we can filter out the spamming warnings.

**Comment by vmalloc** [comment]
+1 - agreed. Will try to get to it when possible

**Comment by yotamr** [comment]
Thanks!

**Comment by vmalloc** [comment]
Current plan is to add `slash.ignore_warnings(message=None, category=None, module=None, lineno=None)`. Unlike `warnings.filterwarnings`, `None` here *does not* mean "match anything". Sounds good?

**Comment by yotamr** [comment]
Looks good, thanks!

**Comment by vmalloc** [comment]
Sure, np!
