### ISSUE TITLE
Allow use of ``timestamp`` in log path formatting

### ISSUE THREAD

**Issue by ViktorFagerlind** [getslash/slash#755]
I would like to store logfiles in a directory with the time and date of the session start. I tried to do this by registring the before_session_start hook and configuring log.session_subpath/log.subpath. This however only worked the tests, the session logfile seems to be opened before this.

Is there another hook to capture before the session or maybe some property from which to extract the current date/time?

**Comment by vmalloc** [comment]
I think what you're asking is to be able to format the session's or test's start_time with something like strftime? If that is the case, adding start_datetime and end_datetime for both sessions and tests will allow you to use the default subpath formatting for this...

**Comment by ViktorFagerlind** [comment]
Yes, exactly, something like that would be great!

Using the IDs to create unique files/folders is a little messy since it is hard to know which files/folders are recent and old (cant trust the dating if files are modified)

**Comment by vmalloc** [comment]
Ok, so I'm changing the issue summary to "add session.start_datetime and test.start_datetime". Since it's really simple I'll add it to the upcoming release (1.5)

**Comment by ViktorFagerlind** [comment]
Perfect!

**Comment by vmalloc** [comment]
Ok, so adding start_time and end_time turned out to involve a lot more fine details than I expected, so I'm postponing that for now. Instead, we will just add the ability to use `timestamp` in your log path formats. For example, `log.subpath` can be `/log/directory/test-{timestamp:%Y-%m-%d-%H%M%S}.log`

I guess that would suit your needs, right?

**Comment by ViktorFagerlind** [comment]
Yes, that's exactly what i need.
