### ISSUE TITLE
Can't find 'slash' command after 'pip install slash' 

### ISSUE THREAD

**Issue by sshuguan** [getslash/slash#819]
I have installed WSL Ubuntu 18.04 on my PC. From the Ubuntu shell, I have installed python2.7 and then 'pip install slash' (successfully). But I do not see 'slash' command in any bin folder (such as /usr/bin, /usr/local/bin, etc.). What could be wrong ? (googled the issue and didn't locate any answers)

**Comment by vmalloc** [comment]
@sshuguan thanks for reporting.

From the sound of it, it sounds it could be an issue related to setuptools and/or pip.

Can you please share the exact steps you took to install Python2.7, and in addition:

1. The version of pip you have
2. The version of setuptools you have installed (`pip list | grep setuptools`)

If the steps are easily reproduced on a clean machine I can try and pin-point it further

**Comment by sshuguan** [comment]
install python2.7 commands:
~$ sudo apt update
~$ sudo apt upgrade
~$ sudo apt install python2.7 python-pip
~$ pip2 install slash

(1)
~$ pip2 --version
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
(2)
~$ pip2 list | grep setuptools
DEPRECATION: The default format will switch to columns in the future. You
can use --format=(legacy|columns) (or define a format=(legacy|columns) in
your pip.conf under the [list] section) to disable this warning.
setuptools (40.0.0)

**Comment by vmalloc** [comment]
@sshuguan and does it reproduce on stock Ubuntu 18.04?

**Comment by sshuguan** [comment]
Yes on my WSL. I tried uninstall and install again. The problem is still
there.

**Comment by vmalloc** [comment]
Oh it's the windows subsystem... Interesting.

Will try to reproduce it then.

**Comment by vmalloc** [comment]
I didn't manage to get it to reproduce using your steps... Perhaps you had some previous commands that caused this issue?

Can you try `sudo pip install -U setuptools` and see if it solves anything?

**Comment by vmalloc** [comment]
@sshuguan I just tried again on a clean install *without* going through 3.x first. I just entered the steps you mentioned without any other command, and it installs fine (btw I got pip 8.1 and not 9.0.1 as you showed). Plus this is a different PC than the one I tried last night.

If you have a set of steps to reproduce on a clean system please share them here... otherwise I'm assuming there's some history to your machine that caused the issue
