### ISSUE TITLE
Support display mode configuration for light backgrounds

### ISSUE THREAD

**Issue by drrlvn** [getslash/slash#925]
For example, the "tests collected" line is white without changing the background, making it unreadable when background isn't dark.

**Comment by drrlvn** [comment]
A configuration for dark/bright background is a good option. For example in VIM there's a setting: `set background=light`.

**Comment by drrlvn** [comment]
The fix only partially solved the issue - a lot of the output is still unreadable or invisible.

Also, I still think a configuration option is a better solution than just setting the background to black.

**Comment by vmalloc** [comment]
Ah I misunderstood what you meant
