### ISSUE TITLE
Is there a way to pass parameter from test_ to a fixture?

### ISSUE THREAD

**Issue by echobravo2** [getslash/slash#944]
I have a fixture that would install some package on the target. There are many packages to install.
I'd like to pass a package name from the test case routine (test_xxx) into the fixture:

class Test():
    def before(self, install_pkg):
    {
    }
   def test_xxx(package_name):
   {
   }

slashconf.py:
def install_pkg(package_name):
{
}

Is there a way to pass the "package_name" parameter from test_xxx to its fixture - install_pkg?

Thanks!

**Comment by vmalloc** [comment]
Unfortunately since fixtures are expanded prior to test execution this is not directly possible. The pattern recommended to achieve this is to have a dual-phase construction, for example

```
@slash.fixture
def package():
    class Package:
        def __init__(self):
            # some initial setup

        def install(self, *args):
            # actual installation
    return Package()

def test_installation(package):
    install_arg = compute_install_arg()
    package.install(install_arg)
```

**Comment by ashapir3** [comment]
I've defined  
def test_installation(package):
in my test file.

The package fixture is defined in fixture related file.

in this example when calling from the test file the:
package.install(install_arg)

there is an error:
E: <Error: AttributeError: 'function' object has no attribute 'install'>, Test: <tests\...

ipdb> package
<function package at 0x00000160DD0A0D08>
ipdb> dir(package)
['__annotations__', '__call__', '__class__', '__closure__', '__code__', '__defaults__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__get__', '__getattribute__', '__globals__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__kwdefaults__', '__le__', '__lt__', '__module__', '__name__', '__ne__', '__new__', '__qualname__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__slash_fixture__', '__str__', '__subclasshook__']

appreciate letting me know how to access the 'install' method of the Package class from the test?

**Comment by vmalloc** [comment]
@ashapir3 you have to have your test receive `package` as a parameter in order for Slash to detect it needs it. That's how fixture dependency discovery works.

**Comment by ashapir3** [comment]
got this working with below:
In my slashconf.py I’ve defined the fixture as below:

@slash.fixture(scope='session', autouse=True)
def package(this):

    class Package:
        dct = {}
        def __init__(self, *args, **kwargs):
            for key, value in kwargs.items():
                self.dct[key] = value

        def install(self):
		    self.obj = Module().process_dict(self.dct)
            status = self.obj.connect()
            if connect_status:
                return True
            else:
                return False

        @this.add_cleanup
        def cleanup():
            Module().disconnect()

    return Package

In the test itself, the fixture won’t set in the begin as we don’t want that fixture to be with the test scope, rather with the session scope:

class Mytest():

    def before(self, fixture1, …):
        pass

    def after(self):
                pass

    def test_installation(self, package):
        kwargs = {"key1": self.value1,
                  "key2": self.value2,
                  "key3": self.value3,
                  "key4": "value4"
                 }

        package(**kwargs).install()

When the test runs, we get the fixture set properly and cleanup is also done automatically

going back to issue [953](https://github.com/getslash/slash/issues/953)

**Comment by vmalloc** [comment]
Can this issue be closed then?

**Comment by ashapir3** [comment]
yep, thank you!
