### ISSUE TITLE
Python3.6 slash.parametrize Error: TypeError: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by ashapir3** [getslash/slash#946]
In Python 3.6, when passing parametrize values, there is a TypeError :  cannot use a string pattern on a bytes-like object>, Test: <tests\....

    @slash.parametrize('fruit', ['apple', 'banana', 'mango', 'ananas'])
    def test_all_fruits(self, fruit):
        fruit_pref = more_set.open_fruit_preferences()
        if not fruit_pref.select(fruit):
            slash.add_failure("failed to select <%s>" % alert)
        if not alert_pref.unselect(fruit):
            slash.add_failure("failed to unselect <%s>" % alert)

I tried converting the strings into bytes with several options below; the same error exists.

    @slash.parametrize('fruit',
                       [b'apple', b'banana', b'mango', b'ananas'])
---
    @slash.parametrize('fruit',
                       ['apple'.encode("utf-8"), 'banana'.encode("utf-8"), 'mango'.encode("utf-8"), 'ananas'.encode("utf-8")])
---
    @slash.parametrize('fruit',
                       [bytes('apple', 'utf-8'), bytes('banana', 'utf-8'), bytes('mango', 'utf-8'), bytes('ananas', 'utf-8')])

The original code used to work in Python 2.7 with no issues.

Thanks!

**Comment by vmalloc** [comment]
Thanks for reporting!

Does it reproduce on a simple example project? (No plugins/addons/hooks)?

**Comment by vmalloc** [comment]
Something does not add up in your original code. All strings visible are not bytes. 

Can you share the exact offending line in the traceback? Alternatively a standalone, simple reproduction of the issue will help us investigate.

**Comment by ashapir3** [comment]
we have several fixtures in before(); when these fixtures not in use as below sample code, I don't see any issue:

import slash
import time
import squish as _squish
from slash_step import STEP
from sync_test_lib.common_util.slash_squish_test import SquishTestBase

class FruitTests(SquishTestBase):

    @slash.parametrize('fruit', ['apple', 'banana', 'mango', 'pineapple'])
    def test_all_fruits(self, fruit):
        pass

---
when adding the before(), then we get the error:
    def before(self, fixture1, fixture2, fixture3, fixture4):
        pass

[2019-05-17 12:39:16] Error Found: TypeError: cannot use a string pattern on a bytes-like object,
Screenshot captured: test_fail_2019-05-17_16-39-13.874716.png
E: <Error: TypeError: cannot use a string pattern on a bytes-like object>, Test: <tests\navaccept\fruits.py:FruitTests.test_all_fruits(fruit=apple)>

apparently, removing the last fixture fixes the issue; investigating that fixture reveal that there is actually an issue with TypeError.
This isn't actually an issue with the parametrize but with the fixture failure.

Sorry for the false alarm, and appreciate your prompt responses!

**Comment by vmalloc** [comment]
sure, no worries.
