### ISSUE TITLE
Add top-level getter for current scope

### ISSUE THREAD

**Issue by drrlvn** [getslash/slash#952]
The only way I could find is `slash.context.session.scope_manager.get_current_stack()[-1]` which is not very friendly.

Maybe some top-level method could be added to get the current scope?

**Comment by ayalash** [comment]
@vmalloc Any objections or can I implement it?

**Comment by vmalloc** [comment]
No objections

**Comment by ayalash** [comment]
@vmalloc During add unittests for this issue I found an odd behavior. 
For the following test file:
```
import slash

def _print_currnet_scope(message):
    slash.logger.notice(message, slash.get_current_scope())

def test_me():
    _print_currnet_scope('During test, current scope: {}')
    for scope_name in ('test', 'module', 'session'):
        slash.add_cleanup(_print_currnet_scope, scope=scope_name,
                          args=(f"During cleanups of {scope_name}, current scope: {{}}",))
```
The output is:
```
$ slash run test_me.py -v
1 tests collected   
[2019-05-31 10:41:27] #1: test_me.py:test_ayalas
[2019-05-31 10:41:27] During test, current scope: test
[2019-05-31 10:41:27] During cleanups of test, current scope: module
[2019-05-31 10:41:27] During cleanups of module, current scope: session
[2019-05-31 10:41:27] During cleanups of session, current scope: None
============================================================ Session ended. 1 successful, 0 skipped, 0 failed, 0 erroneous. Total duration: 00:00:00 =============================================================
```
Which means that during cleanups of all scopes we already pop the scope.
Is it by design? If so, why?

**Comment by vmalloc** [comment]
I'm not sure if memory serves but it was something about the fact that cleanups could, in theory, be registered from within cleanups. A `git blame` on the relevant code might shed some more light on the reason why
