### ISSUE TITLE
before() and after() at session level

### ISSUE THREAD

**Issue by ashapir3** [getslash/slash#953]
before()
Gets called before each separate case from this test class executed,

after()
Gets called after each separate case from this test class executed,

these methods called on the test level scope.
I need to execute some set only once per session.
Do we have the same methods that run on a session level - once per entire test?

**Comment by vmalloc** [comment]
It sounds like what you need is fixtures with `autouse=True` and `scope="session"`?

**Comment by ashapir3** [comment]
there is a dependency on the issue [944](https://github.com/getslash/slash/issues/944)
I've commented there. thanks!

**Comment by ashapir3** [comment]
just commented on the issue [944](https://github.com/getslash/slash/issues/944)

The only problem with this is that this fixture must run as test_ with the fixture it needs to start as a parameter.
I was hoping to have standalone routines for initialization/cleanup (as begin and after) but for a session level. BTW, [unittest ](https://docs.python.org/3/library/unittest.html) has these kind routines:

Test-case scope:
setUp()
tearDown()

Session scope:
setUpClass()
tearDownClass()

I tried to set session scope in an __init__() method in the test class and pass the fixture to it, but it didn't work. 

Is it possible to add session init routines as the approach taken here is too complex for something that should be intuitive?

**Comment by ashapir3** [comment]
This sounds a bit odd, but if you just create a function, not a fixture… and call it from your test, it will get executed first.

import slash

def foo():
    print("Hello, Foo!")

class TestMe(slash.Test):

    foo()
    def test_one(self):
        assert True

    def test_two(self):
        assert True

slash run -vv test_me.py
Hello, Foo!
2 tests collected
[2019-06-03 21:39:19] #1: test_me.py:TestMe.test_one
[2019-06-03 21:39:19] #2: test_me.py:TestMe.test_two

The only problem with this approach is we don't have a proper spot to clean up that resource.

**Comment by vmalloc** [comment]
`foo` is called at the module level, which means it gets executed when Slash loads the file for examination... This is the intended behavior...

**Comment by echobravo2** [comment]
Could you please comment on this?
https://github.com/getslash/slash/issues/953#issuecomment-498435054

**Comment by ashapir3** [comment]
already marking the fixtures with `autouse=True`; the process for the step is just too complex.

I'm not asking to turn a specific method into an auto-init step phase, rather than, generic methods like in unittest (setUpClass(), tearDownClass()) that we could put there whatever session level init we want.

**Comment by vmalloc** [comment]
I see... So at the moment this is not a feature we are planning to support. Also, since class-based tests will be phased out at some point in the future I don't think this is a direction we could be pursuing.

Take into account that session-level is a tricky concept when discussing test classes. Classes could inherit from one another, and be located in different modules and at different scopes. This means that the concept of session is very hard to implement in such cases. This is one of the reasons we strongly favor supporting function-based tests -- once the dependency tree is spanned, it is very clear what lives when and at what scope.

**Comment by ashapir3** [comment]
I guess I'll stick with the [944](https://github.com/getslash/slash/issues/944) approach than.
Thank you.
