### ISSUE TITLE
add_cleanup can't access 

### ISSUE THREAD

**Issue by ashapir3** [getslash/slash#955]
The cleanup() below can't access to instance resources defined in this class (via self).
I've defined my own resource cleanup method in that class but these can't be accessed.
Seems only static class object can access its own methods.
Appreciate letting me know to access this class own methods via self.

```
@slash.fixture(scope='session', autouse=True)
def package(this):

    class Package:
    dct = {}

    def __init__(self, *args, **kwargs):
        for key, value in kwargs.items():
            self.dct[key] = value

    def install(self):
	    self.obj = Module().process_dict(self.dct)
        status = self.obj.connect()
        if connect_status:
            return True
        else:
            return False

        def uninstall(self):
                self.uninstall_app(self.dct['param1'], self.dct['param2'], self.dct['param3'])

    @this.add_cleanup
    def cleanup(self):  #TypeError: cleanup() missing 1 required positional argument: 'self'
        self.uninstall(self.....)

return Package
```

**Comment by vmalloc** [comment]
cleanup in your case is not a method - just a function taking `self` as an argument.

**Comment by ashapir3** [comment]
removing `@this.add_cleanup` decorator won't trigger calling the cleanup function
```
        #@this.add_cleanup
        def cleanup(self):
            self.uninstall()
```
how can we turn the cleanup (with the decorator) into a method? is there another way to achieve that?

**Comment by vmalloc** [comment]
You can have the package constructor call `slash.add_cleanup`, for starters, on a method it has. Assuming the package initialization happens inside the test this is guaranteed to work correctly (the main difference between `this.add_cleanup` and `slash.add_cleanup` is that `this.add_cleanup` properly handles cases in which fixtures fail to initialize.

So in your case it would probably be something like:

```python
class Package:

    def install(self):
        ...
        slash.add_cleanup(self.uninstall)
```
