### ISSUE TITLE
A "--collect-only" equivalent to pytest?

### ISSUE THREAD

**Issue by koreno** [getslash/slash#959]
Is there a way to use the filtering flags with `slash list` so that we can see what test would be run given a set of parameters?

**Comment by vmalloc** [comment]
You mean `-k`? What other parameters?

**Comment by koreno** [comment]
the tests directory, and any other flag that could affect the collection of tests (a plugin could potentially perform some additional filtering or even test injection)

**Comment by vmalloc** [comment]
The plugin would affect the collection of `slash list` as well, and `slash list` receives the path to load for listing, so AFAIK this should have you covered

**Comment by koreno** [comment]
and `-k` is accepted?

**Comment by vmalloc** [comment]
correct
