### ISSUE TITLE
'-k' has false results when there is space in the string

### ISSUE THREAD

**Issue by ayalash** [getslash/slash#964]
For example:
```
$ slash list tests -k 'tag:basic-io' --only-tests | wc -l
18
```
While (notice that space between `tag:` and `basic-io`
```
$ slash list tests -k 'tag: basic-io' --only-tests | wc -l
182
```

**Comment by ayalash** [comment]
I found that it is a behavior of `pyparsing`:
```
>>> from slash.utils.pattern_matching import boolExpr
>>> boolExpr.parseString('tag: basic-io')
([< (only tags)>], {})
>>> boolExpr.parseString('tag:basic-io')
([<basic-io (only tags)>], {})
```

**Comment by ayalash** [comment]
@vmalloc I don't really familiar with `pyparsing` can you please share your knowledge? Is it an expected behaaivor from this package?

IMO think it is a bad behavior of slash - What do you think?
(Our session had 182 instead of 18 because of "trailing" space)

**Comment by vmalloc** [comment]
I can take a look

**Comment by vmalloc** [comment]
The thing is that the tokenizer currently assumes a "word" (a filter in this case) cannot stretch across whitespaces, which of course is not true in this case. I'll have to change the parsing rules to allow ":" plus any amount of whitespaces after it...
