### ISSUE TITLE
autouse fixture is not invoked when defined in class

### ISSUE THREAD

**Issue by ramih-saferide** [getslash/slash#989]
I'm trying to convert my project form pytest to slash.
Is there a way to do the following pytest code in slash?

1. autouse fixture in class # might be a bug
2. fixture scope class
3. custom parametrize iteration names

```
def _parametrize(module):
    params = get_module_params(module) # return list of values
    return dict(
        argnames = 'single_scenario', # parameter_name 
        argvalues = params  # values 
        ids = lambda x: generate_unique_id(x)) # can't be fond in slash


class MyBaseTest():
    @pytest.fixture(autouse=True, scope='class')
    def do_stuff(self, connection):
        log.debug('do_stuff before')
        yield 
        log.debug('do_stuff after')

    def start_test(self, single_scenario, connection):
        log.debug('run test...')
  

class Test01(MyBaseTest):
    scenario_module = some_module
    @pytest.mark.parametrize(**_parametrize(scenario_module))
    def test_some_scenarios(self, single_scenario, connection):
        self.start_test(single_scenario, connection)
```

**Comment by vmalloc** [comment]
Fixtures in Slash have to be regular, module-scoped functions. Unfortunately methods are not supported as fixtures at the moment...

**Comment by ramih-saferide** [comment]
@vmalloc ok, so how can I wrap functionality around the parametrize?
currently if I define before and after in the base class they would be called for each parametrize iteration
```
<.venv> ubuntu → play_with_slash $ cat tests/test_1.py 
from slash import parametrize, Test, logger

def d(msg):
    logger.info(f'\033[93;1m{msg}\033[0m')

class Base(Test):
    def before(self):
        d('before')

    def after(self):
        d('after')

class Test01(Base):
    @parametrize('param', [1, 2, 3])
    def test_something(self, param):
        d(f'test {param}')
<.venv> ubuntu → play_with_slash $ slash run -vv .
3 tests collected   
[2019-11-02 11:35:04] #1: ./tests/test_1.py:Test01.test_something(param=1)
[2019-11-02 11:35:05] before
[2019-11-02 11:35:05] test 1
[2019-11-02 11:35:05] after
[2019-11-02 11:35:05] #2: ./tests/test_1.py:Test01.test_something(param=2)
[2019-11-02 11:35:05] before
[2019-11-02 11:35:05] test 2
[2019-11-02 11:35:05] after
[2019-11-02 11:35:05] #3: ./tests/test_1.py:Test01.test_something(param=3)
[2019-11-02 11:35:05] before
[2019-11-02 11:35:05] test 3
[2019-11-02 11:35:05] after
====== Session ended. 3 successful, 0 skipped, 0 failed, 0 erroneous. Total duration: 00:00:00 ======
```

**Comment by vmalloc** [comment]
So you'd like a before/after to call for a single *set* of parameters? Can you give a more concrete/real use case for when you'd like to have such a thing?

**Comment by ramih-saferide** [comment]
@vmalloc sure,
let's say In the "before function" I want to enable access between two systems with specifying from which ip to which ip:port using specific protocol
then to test if it's the only allowed action
then (in after function) to remove this configuration

**Comment by vmalloc** [comment]
I see. Well there are a couple of wayt to go about it, but the simplest one would probably be to have a module-scoped fixture to achieve this. Fixtures with functions are generally preferable to class after/before setups, and we do intend to deprecate class tests at some point in the future as they incur unnecessary complexity to support
